name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.goarch }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download modules
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Build (linux/${{ matrix.goarch }})
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: "0"
        run: |
          mkdir -p dist
          if [[ -f "./cmd/ssh-noti/main.go" ]]; then
            PKG="./cmd/ssh-noti"
          elif [[ -f "./main.go" ]]; then
            PKG="."
          else
            echo "ERROR: Could not locate main.go in ./cmd/ssh-noti or repo root." >&2
            exit 1
          fi
          echo "Building package: $PKG"
          go build -ldflags "-X main.Version=${GITHUB_SHA}" -o dist/ssh-noti_linux_${GOARCH} "$PKG"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-noti_linux_${{ matrix.goarch }}
          path: dist/ssh-noti_linux_${{ matrix.goarch }}
